controller_list:
  - name: fake_pipoudou_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_Link_1
      - Joint_Link_2
      - Joint_Link_3
      - Joint_Link_4
  - name: fake_pipoudou_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - Hand_Link
      - Finger_link_1
      - Finger_link_2
      - Finger_link_3
initial:  # Define initial robot poses per group
  - group: pipoudou_arm
    pose: parcking
  - group: pipoudou_hand
    pose: pince_ferme