pipoudou_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Joint_Link_1
    - Joint_Link_2
    - Joint_Link_3
    - Joint_Link_4
  gains:
    Joint_Link_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_Link_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_Link_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint_Link_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
pipoudou_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Hand_Link
    - Finger_link_1
    - Finger_link_2
    - Finger_link_3
  gains:
    Hand_Link:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Finger_link_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Finger_link_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Finger_link_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1