controller_list:
  - name: pipoudou_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Joint_Link_1
      - Joint_Link_2
      - Joint_Link_3
      - Joint_Link_4
  - name: pipoudou_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - Hand_Link
      - Finger_link_1
      - Finger_link_2
      - Finger_link_3